name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ECR_REGISTRY: 438267616125.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_NAME: opencart-docker
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag Docker image
      id: build-image
      run: |
        docker-compose -f opencart-docker/docker-compose.yml build
        docker tag ${{ env.IMAGE_NAME }}_apache ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}-apache:latest
        docker tag ${{ env.IMAGE_NAME }}_php-fpm ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}-php-fpm:latest

    - name: Push Docker image to ECR
      id: push-image
      run: |
        docker images
        docker push ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}-apache:latest
        docker push ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}-php-fpm:latest


