name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker apache image
      run:  docker build opencart-docker/apache --tag my-apache-image:$(date +%s)
    - uses: actions/checkout@v3
    - name: Build the Docker php-fpm image
      run:  docker build opencart-docker/php-fpm --tag my-php-fpm-image:$(date +%s)

